### ISSUE TITLE
Stub test not working for imaging interface

### ISSUE THREAD

**Issue by alessandratrapani** [catalystneuro/mousev1-to-nwb#10]
This issue is a reminder to investigate why, with the current implementation, even if the stub test option is `True`, the imaging data are saved with the total number of frames.

**Comment by weiglszonja** [comment]
Hmm, I would start debugging with checking what happens if you call `frame_slice()` on the imaging extractor
like : `self.imaging_extractor.frame_slice(start_frame=0, end_frame=stub_frames)`

**Comment by alessandratrapani** [comment]
Bug found, detail in https://github.com/catalystneuro/mousev1-to-nwb/pull/11#discussion_r1471677162
Fixed in 4b4259a72e7deb0c8e583f04139feb0c0237e09d

**Comment by alessandratrapani** [comment]
Bug found, detail in https://github.com/catalystneuro/mousev1-to-nwb/pull/11#discussion_r1471677162
Fixed in 4b4259a72e7deb0c8e583f04139feb0c0237e09d
